name: ion_identity_client_example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.8
  dio:
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  ion_identity_client:
    path: ../

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.10
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1

dependency_overrides:
  js: ^0.7.1

flutter:
  uses-material-design: true
