name: ion_identity_client
version: 0.0.1

publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  asn1lib: ^1.5.4
  bdk_flutter:
    git:
      url: https://github.com/ice-tychon/bdk-flutter.git
      ref: chore/update-flutter-rust-bridge
  blockchain_utils: ^4.1.0
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.5
  crypto_keys: ^0.3.0+1
  cryptography: ^2.7.0
  dio: ^5.7.0
  dio_smart_retry: ^7.0.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  local_auth: ^2.3.0
  local_auth_crypto: ^1.1.1
  on_chain: ^6.0.0
  passkeys: ^2.11.0
  pointycastle: ^3.9.1
  rxdart: ^0.28.0
  sprintf: ^7.0.0
  tonutils: ^0.5.7
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.6.10
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0


dependency_overrides:
  js: ^0.7.1
